forestoration/authentication/routes.py
import functools
from cloudinary.uploader import upload
from forestoration import my_sql, bcrypt
from forestoration.authentication.forms import LoginForm, RegistrationForm
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    session,
    flash,
    g
)

authentication = Blueprint("authentication", __name__)

@authentication.before_app_request
def load_logged_in_user():
    user_email = session.get("user_email")
    connection = my_sql.connect()   
    cursor = connection.cursor()

    if user_email is None:
        g.user = None
    else:
        cursor.execute("""
            SELECT * FROM Individual 
            WHERE email = %s""",  
            (user_email,))
        g.user = cursor.fetchone()
        if not g.user:
            cursor.execute("""
                SELECT * FROM Organization 
                WHERE email = %s""",  
                (user_email,)) 
            g.user = cursor.fetchone()

@authentication.route("/logout")
def logout():
    session.clear()       
    return redirect(url_for("authentication.index"))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("authentication.index"))
        
        return view(**kwargs)
    return wrapped_view

@authentication.route("/", methods=["POST", "GET"])
def index():
    form = LoginForm()
    if request.method == "POST" and form.validate_on_submit():
        connection = my_sql.connect()
        cursor = connection.cursor()

        email = form.email.data
        password = form.password.data
        user_type = form.user_type.data

        if user_type == "Individual":
            cursor.execute("""
                SELECT * FROM Individual 
                WHERE email = %s""", 
                (email,))
            individual = cursor.fetchone()
        
            if individual and bcrypt.check_password_hash(individual[3], password):
                session["user_email"] = email
                return redirect(url_for("individual.individual", 
                                        user_email=individual[2]))
            else:
                flash("One of the credentials you've entered is incorrect. \
                    Please try again.", "danger")
        else:
            cursor.execute("""
                SELECT * FROM Organization 
                WHERE email = %s""", 
                (email,))
            organization = cursor.fetchone()
        
            if organization and bcrypt.check_password_hash(organization[3], password):
                session["user_email"] = email
                return redirect(url_for("organization.org_dashboard", 
                                        user_email=organization[2]))
            else:
                flash("One of the credentials you've entered is incorrect. \
                    Please try again.", "danger")

    return render_template("index.html", 
                            title="Forest Restoration",
                            form=form)

@authentication.route("/register", methods=["POST", "GET"])                                                      
def register():
    form = RegistrationForm()

    if request.method == "POST" and form.validate_on_submit():
        connection = my_sql.connect()
        cursor = connection.cursor()

        email = form.email.data
        user_type = form.user_type.data
        filename = "{}_1".format(email)
        profile_picture = form.profile_picture.data
        organization_or_full_name = form.organization_or_full_name.data
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")

        if profile_picture:
            upload(profile_picture.read(), 
            public_id="forestoration/{}".format(filename))

        if user_type == "Individual":
            cursor.execute("""
                INSERT INTO Individual (`full_name`, `email`, `password`, `filename` ) 
                VALUES (%s, %s, %s, %s)""", 
                (organization_or_full_name, email, hashed_password, filename))
        else:
            cursor.execute("""
                INSERT INTO Organization (`full_name`, `email`, `password`, `filename`) 
                VALUES (%s, %s, %s, %s)""", 
                (organization_or_full_name, email, hashed_password, filename))

        connection.commit()

        flash("Your account has been created successfully.", "success")
        return redirect(url_for("authentication.index"))

    return render_template("register.html",
                            title="Register",
                            form=form)

forestoration/individuals/routes.py
import pymysql
from datetime import datetime
from cloudinary.uploader import upload, destroy
from forestoration.authentication.routes import login_required
from forestoration import my_sql
from forestoration.individuals.forms import *
from forestoration.individuals.manage import *
from flask import (
    Blueprint,
    g,
    flash,
    request,
    session,
    url_for,
    redirect,
    render_template
)

from forestoration.individuals.manage import rating_exists

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])

individuals = Blueprint("individual", __name__)

@individuals.route("/individual/<user_email>", methods=["POST", "GET"])
@login_required
def individual(user_email):
    connection = my_sql.connect()
    cursor = connection.cursor(pymysql.cursors.DictCursor)
    cursor.execute("""
        SELECT * FROM Events 
        WHERE event_id NOT IN 
        (SELECT event_id FROM Participation 
        WHERE individual_id = %s)""",
        g.user[0])
    events = cursor.fetchall()

    return render_template("events.html",
                            title="User Dashboard",
                            events=events)

@individuals.route("/joined/<user_email>", methods=["POST", "GET"])
@login_required
def joined(user_email):
    connection = my_sql.connect()
    cursor = connection.cursor(pymysql.cursors.DictCursor)
    cursor.execute("""
        SELECT * FROM Events 
        WHERE event_id IN 
        (SELECT event_id FROM Participation 
        WHERE individual_id = %s)""",
        g.user[0])
    events = cursor.fetchall()

    return render_template("joined.html",
                            title="User Dashboard",
                            events=events)

@individuals.route("/individual_profile", methods=["POST", "GET"])
@login_required
def individual_profile():
    return render_template("individual_profile.html",
                            title="Individual Profile")

@individuals.route("/join", methods=["POST", "GET"])
@login_required
def join():
    if request.method == "POST":
        connection = my_sql.connect()
        cursor = connection.cursor()
        cursor.execute("""
            INSERT INTO Participation (`event_id`, `individual_id`) 
            VALUES (%s, %s)""",
            (request.form["event_id"], g.user[0]))
        connection.commit()

        flash("We are grateful for your participatory act.", "success")
        return redirect(url_for("individual.individual", user_email=g.user[2]))

@individuals.route("/organization", methods=["POST", "GET"])
@login_required
def organization():
    connection = my_sql.connect()
    cursor = connection.cursor(pymysql.cursors.DictCursor)
    cursor.execute("SELECT * FROM Organization")
    organization = cursor.fetchall()
    
    return render_template("individual_organization.html",
                        organization=organization)

@individuals.route("/inquiry", methods=["POST", "GET"])
@login_required
def inquiry():
    return render_template("inquiry_individual.html",
                            title="Inquiry")

def allowed_file(filename):
	return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@individuals.route("/individual_setting", methods=["POST", "GET"])
@login_required
def individuals_settings():
    email = g.user[2]
    file = request.files.get('file')
    new_name = request.form.get('user_name', False)
    new_email = request.form.get('user_email', False)
    email, filename = g.user[2], g.user[4]
    previous = filename.split("_")
    new = "{}_{}".format(email, int(previous[-1]) + 1)

    if file and allowed_file(file.filename):
        if request.method == "POST":
            destroy(public_id="forestoration/{}".format(filename))
            upload(file.read(), public_id="forestoration/{}".format(new))
            flash("Profile Successfully Updated", "success")

            connection = my_sql.connect()
            cursor = connection.cursor()
            cursor.execute("""
                UPDATE Individual 
                SET full_name = %s, 
                    email = %s, 
                    filename = %s
                    WHERE email = %s""", 
                (new_name, new_email, new, email))
            connection.commit()
    else:
        if request.method == "POST":
            flash("Profile Successfully Updated", "success")
            connection = my_sql.connect()
            cursor = connection.cursor()
            cursor.execute("""
                UPDATE Individual 
                SET full_name = %s, 
                    email = %s
                    WHERE email = %s""", 
                (new_name, new_email, email))
            connection.commit()
    return render_template("individual_profile_setting.html", title="Individual Settings", user=g.user)

@individuals.route("/individual_pass_setting", methods=["POST", "GET"])
@login_required
def individuals_pass_settings():
    email = g.user[2]
    connection = my_sql.connect()
    cursor = connection.cursor()
    cursor.execute("SELECT password FROM individual WHERE email =%s", (email))
    password= cursor.fetchone()
    new_pass = request.form.get('new_pass')
    confirm_pass = request.form.get('confirm_pass')
    old_pass = request.form.get('old_pass')

    if request.method == "POST":
        if bcrypt.check_password_hash(password[0], old_pass) and new_pass == confirm_pass:
                        hashed_password = bcrypt.generate_password_hash(new_pass).decode("utf-8")
                        cursor.execute("""UPDATE individual set password=%s WHERE email=%s""", (hashed_password, email))
                        connection.commit()
                        flash("Password Successfully Updated", "success")
        elif not new_pass or not old_pass or not confirm_pass:
                    flash("All fields required", "danger")
        else:
            flash("One of the credentials you've entered is incorrect. Please try again.",
                                "error")
    return render_template("individual_pass_setting.html", title="Individual Settings")

@individuals.route("/individual_notif_setting", methods=["POST", "GET"])
@login_required
def individuals_notif_settings():
    return render_template("individual_notif_setting.html", title="Individual Settings")

@individuals.route('/rate/<event_id>', methods=['POST', 'GET'])
def rate(event_id):
    individual = g.user[0]

    connection = my_sql.connect()
    cursor = connection.cursor(pymysql.cursors.DictCursor)
    if rating_exists(individual, event_id):
        return redirect(f"/edit-rating/{event_id}")
    
    form = RatingForm()
    if form.validate_on_submit():
        query = """
                INSERT INTO `Rating` (
                    `individual_id`,
                    `event_id`,
                    `rating_review`,
                    `rating_rating`,
                    `rating_date`
                    )
                VALUES (%s, %s, %s, %s, %s)
                """
        data = (                    
                individual,
                event_id,
                form.review.data,
                form.rating.data,
                datetime.now().strftime('%Y-%m-%d')
                )
        cursor.execute(query, data)
        cursor.close()
        connection.commit()
        connection.close()
        update_rating(event_id)
        flash('The event is rated successfully', 'success')
        return redirect('/i-rated')
    else:
        return render_template('rating_individual.html', form=form, event_name=get_event_name(event_id))

@individuals.route('/edit-rating/<event_id>', methods=['POST', 'GET'])
def edit_rating(event_id):
    individual = g.user[0]
    connection = my_sql.connect()
    cursor = connection.cursor(pymysql.cursors.DictCursor)
    cursor.execute("""
        SELECT rating_review AS review,
                rating_rating AS rating,
                individual_id,
                event_id
        FROM Rating
        WHERE individual_id = %s AND event_id = %s""", (individual, event_id))
        
    rating_info = cursor.fetchone()
    cursor.close()
    connection.commit()
    connection.close()

    if individual != rating_info['individual_id']:
        message = flash("No rating found", "warning")
        return message
    else:
        form = RatingForm(data=rating_info)
            
        if form.validate_on_submit():
            query = """
                UPDATE Rating 
                SET rating_review = %s,
                    rating_rating = %s,
                    rating_date = %s
                WHERE individual_id = %s AND event_id = %s
                """

            data = (form.review.data,
                    form.rating.data,
                    datetime.now().strftime('%Y-%m-%d'),                
                    individual,
                    event_id,
                )
            connection = my_sql.connect()
            cursor = connection.cursor(pymysql.cursors.DictCursor)
            cursor.execute(query, data)
            cursor.close()
            connection.commit()
            connection.close()

            update_rating(event_id)
            flash('The rating is updated successfully', 'success')
            return redirect('/i-rated')
        else:
            return render_template("individual_edit_rating.html", form=form, event_name=get_event_name(event_id))

@individuals.route('/i-rated', methods=['POST', 'GET'])
def i_rated():
    individual = g.user[0]
    i_rated = all_events_i_rated(individual)
    return render_template("individual_rating_page.html", i_rated=i_rated)

@individuals.route('/delete-rating/<event_id>', methods=['POST', 'GET'])
def delete_rating(event_id):
    individual = g.user[0]
    connection = my_sql.connect()
    cursor = connection.cursor(pymysql.cursors.DictCursor)
    cursor.execute("""
        SELECT rating_review,
                    rating_rating,
                    rating_date,
                    individual_id,
                    event_id

forestoration/templates/events.html
{% extends "individual_page.html" %} 
{% block links %}
  <link
    rel="stylesheet"
    href="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.css"
  />
  <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
  ></script>

  <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>
  <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/extensions/custom-view/bootstrap-table-custom-view.js"></script>
  <script>
    $(function () {
      $("#table").bootstrapTable({
        data: JSON.parse('{{ events | tojson | safe}}')
      })
    })

    function customViewFormatter(data) {
      var template = $("#eventTemplate").html();
      var view = "";
      $.each(data, function (i, row) {
        view += template
          .replaceAll("%EVENT_ID%", row.event_id)
          .replaceAll("%OWNER%", row.owner)
          .replaceAll("%EVENT_NAME%", row.event_name)
          .replaceAll("%EVENT_DESCRIPTION%", row.event_description)
          .replaceAll("%NUMBER_OF_PARTICIPANTS%", row.number_of_participants)
          .replaceAll("%NUMBER_OF_SEEDS%", row.number_of_seeds)
          .replaceAll("%VENUE%", row.venue)
          .replaceAll("%SEEDLING%", row.seedling)
          .replaceAll("%START_DATE%", row.start_date)
          .replaceAll("%END_DATE%", row.end_date);
      });

      return `<div class="row mx-0">${view}</div>`;
    }
  </script>
{% endblock %}

{% block content %}
  <div class="container-fluid d-flex align-content-center flex-wrap">
    <div class="container my-5">
      <table
        id="table"
        data-search="true"
        data-pagination="true"
        data-page-size="3"
        data-show-custom-view="true"
        data-custom-view="customViewFormatter"
        data-show-custom-view-button="true"
      >
        <thead>
          <tr>
            <th data-field="event_name">Event Name</th>
            <th data-field="event_description">Event Description</th>
            <th data-field="number_of_participants">Number of Participants</th>
            <th data-field="number_of_seeds">Number of Seeds</th>
            <th data-field="venue">Venue</th>
            <th data-field="cost">Cost</th>
            <th data-field="start_date">Start Date</th>
            <th data-field="end_date">End Date</th>
          </tr>
        </thead>
      </table>

      <template id="eventTemplate">
        <div class="col-4 mt-3">
          <div class="card shadow bg-white rounded">
            <div class="card-body">
              <div class="row">
                <div class="col-12 col-lg-8 col-md-6">
                  <h5 class="mb-0 text-truncated">Organizational Event</h5>
                  <p class="lead"><i>%EVENT_NAME%</i></p>
                  <p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                    Beatae, provident?
                  </p>
                </div>
                <div class="col-12 col-lg-4 col-md-6 text-center">
                  <br />
                  <ul class="list-inline ratings text-center" title="Ratings">
                    <li class="list-inline-item">
                      <a href="#"
                        ><span class="fa fa-star text-success"></span
                      ></a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#"
                        ><span class="fa fa-star text-success"></span
                      ></a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#"
                        ><span class="fa fa-star text-success"></span
                      ></a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#"
                        ><span class="fa fa-star text-success"></span
                      ></a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#"
                        ><span class="fa fa-star text-success"></span
                      ></a>
                    </li>
                  </ul>
                </div>
                <div class="col-12 col-md-6">
                  <h6 class="mb-0 fw-bold">%START_DATE%</h6>
                  <small>Start Date</small>
                </div>
                <div class="col-12 col-md-6">
                  <h6 class="mb-0 fw-bold">%END_DATE%</h6>
                  <small>End Date</small>
                </div>
                <div class="col-md-12 mt-3 text-end">
                  <a class="text-primary h5 text-decoration-none" data-bs-toggle="modal" data-bs-target="#modal-%EVENT_ID%" href="#">
                    View
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="modal-%EVENT_ID%" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">%EVENT_NAME%</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p class="display-6">Objectives</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam officiis eligendi velit, nesciunt in obcaecati perferendis, ex eaque, dicta reiciendis neque blanditiis natus voluptatem consectetur! Ad similique itaque id corporis repellat repellendus asperiores sed adipisci, optio voluptates natus error doloremque rem corrupti libero assumenda iure iusto? Sunt laborum praesentium eligendi inventore nobis tempore consequatur odio incidunt sit voluptates laudantium corporis dolorem voluptatum debitis perferendis dignissimos aut illum nam aperiam, officia provident repellat repudiandae magnam ullam? Inventore quasi eligendi mollitia ea, molestiae esse sint recusandae saepe illum provident cum aliquid iusto tempore, possimus reiciendis officiis excepturi sed! Mollitia velit sed minus odio libero. Adipisci nobis delectus voluptatibus mollitia corrupti quis dolor itaque beatae! Qui consequatur necessitatibus porro quasi architecto libero cumque nam vitae. Ducimus veniam exercitationem quo vero deleniti voluptatibus aspernatur temporibus eveniet suscipit minima dicta laudantium mollitia, porro atque dignissimos nam. Quam incidunt similique fugit voluptate totam illo perferendis tenetur.</p>
                <p>
                  <span class="badge badge-info tags">Venue: %VENUE%</span>
                  <span class="badge badge-info tags">Seedling: %SEEDLING%</span>
                </p>
                <p>
                  <span class="badge badge-info tags">Number of Seeds: %NUMBER_OF_SEEDS%</span>
                  <span class="badge badge-info tags">Number of Participants: %NUMBER_OF_PARTICIPANTS%</span>
                </p>
              </div>
              <div class="modal-footer">
                <p class="small text-muted">What are you waiting for?</p>
                <form action="{{ url_for('individual.join') }}" method="POST">
                  <input class="d-none" name="event_id" id="event_id" type="text" value="%EVENT_ID%">
                  <input type="submit" value="Join Now" class="btn btn-outline-success">
                </form>
              </div>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
{% endblock %}

forestoration/templates/index.html
{% extends "layout.html" %} {% block content %} {% with messages =
get_flashed_messages(with_categories=true) %} {% if messages %} {% for category,
message in messages %}
<div class="container mt-5">
  <div class="alert alert-{{ category }}" role="alert">
    <strong>{{ message }}</strong>
  </div>
</div>
{% endfor %} {% endif %} {% endwith %}

<div
  id="introduction"
  class="container-fluid vh-100 d-flex align-content-center flex-wrap"
>
  <div class="container-fluid vh-100 d-flex align-content-center flex-wrap">
    <div class="row g-4 justify-content-center align-items-center">
      <div class="col-md-5 text-center text-md-start">
        <img
          src="{{ url_for('static', filename='images/second.png') }}"
          alt=""
          class="img-fluid"
        />
      </div>
      <div class="col-md-6">
        <h1>
          <div class="display-2">Move</div>
          <div class="display-5 text-muted">Let's save our homes.</div>
        </h1>
        <p class="lead my-4 text-muted">
          A measured approach that considers much more than just planting trees.
        </p>
        <a
          href="{{ url_for('authentication.register') }}"
          class="text-success text-decoration-none h5 fw-bold"
          >Register Now</a
        >
      </div>
    </div>
  </div>
</div>

<!-- About Us -->
<div
  id="about-us"
  class="container-fluid vh-100 d-flex align-content-center flex-wrap"
>
  <div class="container">
    <div class="row g-4 justify-content-center align-items-center">
      <div class="col-md-6">
        <h1>
          <div class="display-2">About Us</div>
          <div class="display-5 text-muted"></div>
        </h1>
        <p class="lead my-4 text-muted">
          <span class="text-secondary fw-bold">Forest Restoration</span> is a
          platform that allows you to plant a
          <span class="text-success fw-bold">tree</span> from a distance and follow the
          project's story online.
        </p>
      </div>
      <div class="col-md-5 text-center text-md-start">
        <img
          src="{{ url_for('static', filename='images/sixth.png') }}"
          alt=""
          class="img-fluid"
        />
      </div>
    </div>
  </div>
</div>

<!-- Contact Us -->
<div
  id="impact"
  class="container-fluid vh-100 d-flex align-content-center flex-wrap"
>
  <div class="container d-flex align-content-center flex-wrap">
    <div
      class="row align-items-center justify-content-center align-content-center"
    >
      <div class="col-md-5 text-center text-md-start">
        <img
          src="{{ url_for('static', filename='images/fifth.png') }}"
          alt=""
          class="img-fluid"
        />
      </div>
      <div class="col-md-6">
        <h1>
          <div class="display-2">Explore</div>
          <div class="display-5 text-muted">Every tree in the right way.</div>
        </h1>
        <p class="lead my-4 text-muted">
          We believe that every one of us must make an effort to diminish our
          CO2 emissions, and in doing so, we can also help absorb them by
          planting <span class="text-success fw-bold">trees</span>.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div
  class="modal fade"
  id="reg-modal"
  tabindex="-1"
  aria-labelledby="modal-title"
  aria-hidden="true"
>
  <div class="modal-dialog shadow bg-white rounded">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-title">
          <i class="bi bi-box-arrow-in-right"></i> Login or Sign Up
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form method="POST" class="lead">
          {{ form.hidden_tag() }} {{ form.email.label(class="form-label") }}
          <div class="input-group">
            <span class="input-group-text">
              <i class="bi bi-envelope text-secondary"></i>
            </span>
            {% if form.email.errors %} {{ form.email(class="form-control
            form-control-sm is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span>{{error}}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.email(class="form-control form-control-sm") }} {%
            endif %}
          </div>
          {{ form.password.label(class="form-label") }}
          <div class="input-group">
            <span class="input-group-text">
              <i class="bi bi-key text-secondary"></i>
            </span>
            {% if form.password.errors %} {{ form.password(class="form-control
            form-control-sm is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
              <span>{{error}}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.password(class="form-control form-control-sm") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.user_type.label(class="form-control-label mb-2") }} {{
            form.user_type(class="form-select form-control-sm text-muted") }}
          </div>
          <div class="form-group pt-3 d-grid gap-2">
            {{ form.login(class="btn text-success px-5 rounded-pill shadow")}}
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <p class="text-muted">Don't have an account yet?</p>
        <a
          href="{{ url_for('authentication.register') }}"
          class="text-decoration-none"
          >Sign Up</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock content %}

forestoration/templates/individual_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
    />
    <link rel="stylesheet" href="/static/css/individual.css" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
      integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
      integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
      crossorigin="anonymous"
    ></script>

    {% block links %}
    {% endblock %}
  </head>
  <body>
    {% include "navigation_bar_individual.html" %}

    {% include "sidebar.html" %} 
    
    {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %} 
        {% for category, message in messages %}
          <div class="container mt-5">
            <div class="alert alert-{{ category }}" role="alert">
              <strong>{{ message }}</strong>
            </div>
          </div>
        {% endfor %} 
      {% endif %} 
    {% endwith %}

    {% block content %} 
    {% endblock %}
  </body>
</html>

forestoration/templates/individual_setting.html
{% extends "individual_page.html" %} {% block content %}
<section class="settings">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="left shadow">
          <span class="head">User Settings</span>
          <nav class="set flex-column">
            <a
              class="nav-link"
              aria-current="page"
              href="{{ url_for('individual.individuals_settings', user_email=g.user[1]) }}"
              >Org Profile</a
            >
            <a
              class="nav-link"
              aria-current="page"
              href="{{ url_for('individual.individuals_pass_settings', user_email=g.user[1]) }}"
              >Change Password</a
            >
            <a
              class="nav-link"
              aria-current="page"
              href="{{ url_for('individual.individuals_notif_settings', user_email=g.user[1]) }}"
              >Notification</a
            >
          </nav>
        </div>
      </div>
      <div class="col-8">{% block prof %} {% endblock prof %}</div>
    </div>
  </div>
</section>
{% endblock content%}